# multiple targets for a rule and the commands will run for each target  $@ is the automatic varible that contain the target name

all: f1.o f2.o

f1.o f2.o:
	echo $@

#equivqlent to
#f1.o:
#	echo f1.o
#f2.o:
#	echo f2.o
